export const Select_background_color = 'SELECTBACKGROUNDCOLOR'
export const change_vectore = 'CHANGEVECTORE'
export const checkLayout = 'CHECKLAYOUT'
export const setLayout = 'SETLAYOUT'
export const setAnswer = 'SETANSWER'